CREATE OR REPLACE TABLE SALES (
    WEEK NUMBER,
    REVENUE NUMBER,
    SKU STRING,
    REGION STRING
);

CREATE OR REPLACE TABLE INVENTORY (
    SKU STRING,
    STOCKOUT BOOLEAN,
    WEEK NUMBER
);

CREATE OR REPLACE TABLE SUPPORT_TICKETS (
    WEEK NUMBER,
    ISSUE_TYPE STRING,
    SEVERITY STRING
);
