CREATE TAG classification;
CREATE TAG sensitivity;

ALTER TABLE SALES ADD TAG sensitivity = 'PUBLIC';
ALTER TABLE INVENTORY ADD TAG sensitivity = 'INTERNAL';
ALTER TABLE SUPPORT_TICKETS ADD TAG sensitivity = 'CONFIDENTIAL';
